version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"
    networks:
      - helpcenter_network

  helpcenter-bff:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: helpcenter_bff_service
    ports:
      - "8080:8080"
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - OKTA_ORG_URL=https://dev-example.okta.com
      - OKTA_CLIENT_TOKEN=your-okta-token
    depends_on:
      - redis
    networks:
      - helpcenter_network

networks:
  helpcenter_network:
    driver: bridge
