server:
  port: 8080

okta:
  client:
    orgUrl: ${OKTA_ORG_URL}
    token: ${OKTA_CLIENT_TOKEN}

spring:
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      password: ${SPRING_REDIS_PASSWORD:}
      port: ${SPRING_REDIS_PORT:6379}
      timeout: 5000
